name: JSON check
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-check
        run: |
          echo "Listing Changed JSON Files"
          FILES=$(git diff --name-only main HEAD | grep "json")
          echo "$FILES"
          echo "$FILES" | xargs -n1 -I {} python -m json.tool {}
